#!/usr/bin/env bash
#Creates a file and its own id

end_process() {
    rm /var/run/myscript.pid
    exit
    }

echo '$$' > /var/run/myscript.pid

while true
do
    echo "To infinity and beyond"
    sleep 2
    trap 'echo "I hate the kill command" && end_process' SIGTERM
    trap 'echo "Y U no love me?!"' SIGINT
    trap 'end_process' SIGQUIT
done
