#!/usr/bin/env bash
#This script reads the content of a password file

while IFS=: read -r username _ userid _ homedir _
do
    echo "$username"
    echo "$userid"
    echo "$homedir"
done < /etc/passwd
