#!/usr/bin/env bash
#tells a story with content of password file

while IFS=: read -r username passwd userid grid info homedir shell
do
    echo "The user $username is part of the $grid gang, " \
    "lives in $homedir and rides $shell. "\
    "$userid place is protected by the passcode $passwd, " \
    "more info about the user here: $info"
done < "/etc/passwd"
