#!/usr/bin/env bash
# Script displays  "Best School" 10 times with while loop and if

counter=0

while [ $counter -lt 10 ]; do

    if [ $counter -eq 9 ]; then
        echo "Hi"
    fi

    echo "Best School"

    ((counter++))
done
