#!/usr/bin/env bash
#configuring a ufw to deny incoming traffic
#and select ports

sudo apt-get update -y
sudo apt-get install ufw -y

sudo ufw default deny incoming
sudo ufw default allow outgoing

sudo ufw allow ssh
sudo ufw allow http
sudo ufw allow https

sudo ufw enable
sudo ufw status
